### ISSUE TITLE
i cant logg requests in preview mode altough /data returns 200 and timestap + event id

### ISSUE THREAD

**Issue by jiggyjo11** [stape-io/data-client#12]
I deplyed the data tag on gtm server and getting a `200` response when sending requests via postman. However, I am not able to logg the post request or fire any triggers. Pls help! 

![image](https://github.com/user-attachments/assets/f3d335a6-4ecc-4faf-ab9b-474b8efceb86)
![image](https://github.com/user-attachments/assets/91c24daa-db3c-4500-bcc1-07daf15ab51c)

**Comment by alexbub** [comment]
If you are sending requests from postman, here is an article on how to debug such requests: https://stape.io/blog/debug-webhooks-google-tag-manager-server

You can find many articles on our blog and also check out our community: https://community.stape.io/
