### ISSUE TITLE
Add variables to response body

### ISSUE THREAD

**Issue by Larsfriishansen** [stape-io/data-client#6]
We would like to be able to add variables as part of the response body: 

Use case: 
We want to return the users country to client side GTM based on the GEO-ip headers.

1. Send event from client side data tag to SS GTM
2. SS GTM gets country bases on GEO-ip header
3. SS GTM respons Client side GTM, with the dataLayer event
4. The country is a variable of the dataLayer event

![image](https://github.com/stape-io/data-client/assets/107996813/fa7007a4-0ee6-4c8e-864c-8d94094ef474)

**Comment by Bukashk0zzz** [comment]
You already can do this. 
Please check https://stape.io/blog/send-datalayer-push-from-server-gtm-to-web-gtm

**Comment by Larsfriishansen** [comment]
Great. Thanks Dennis
